# Assignment - 1

### Section 1

In [2]:
## •
import numpy as np
import math

In [3]:
## •
a = 1/math.sqrt(2)
b = 1/math.sqrt(2)

In [4]:
## •
c = np.array([a,b])

In [10]:
## •
is_normalized = np.isclose(a**2 + b**2, 1)
if(is_normalized):
  print("Normalised vector")
else:
  print("Vector is not normalised")

Normalised vector


In [15]:
## •
length = len(c)
length

2

In [18]:
## if unit length of vector is asked
length1 = np.linalg.norm(c)
print(length1)

0.9999999999999999


### Section 2

In [22]:
## •
n = int(input("Enter number of elements : "))
vec = np.array([int(input()) for _ in range(n)])
print(vec)

Enter number of elements : 2
5
6
[5 6]


In [34]:
## •
def is_normalised(v):
  return np.isclose(np.linalg.norm(v),1)

print("Is Normalized:", is_normalised(vec))

Is Normalized: False


In [32]:
## •
def Product(A,B):
  dot = np.dot(A,B)
  cross = np.cross(A,B)
  return dot,cross

x = np.array([1, 2, 3])
y = np.array([4,5,6])
dot,cross = Product(x,y)
print(dot)
print(cross)

32
[-3  6 -3]


In [28]:
## •
def unit_vector(a):
  return a/np.linalg.norm(a)

print(unit_vector(vec))

[0.6401844  0.76822128]


### Section 3

In [38]:
## •
rows = int(input("Enter the no. of rows : "))
cols = int(input("Enter the no. of cols : "))
mat = np.array([[int(input()) for _ in range(cols)] for _ in range(rows)])
print(mat)

Enter the no. of rows : 2
Enter the no. of cols : 2
1
2
3
4
[[1 2]
 [3 4]]


In [40]:
## •
print(mat.T)

[[1 3]
 [2 4]]


In [44]:
if(rows == cols):
  ## •
  print("Determinant : ",np.linalg.det(mat))

  ## •
  print("Rank : ",np.linalg.matrix_rank(mat))

  ## •
  print("Trace : ",np.trace(mat))

  ## •
  eigenvalues,eigenvector = np.linalg.eig(mat)
  print("Eigenvalues : ",eigenvalues)
  print("Eigenvector : \n",eigenvector)

  ## •
  if(np.linalg.det(mat) != 0):
    print("Inverse : \n",np.linalg.inv(mat))
  else:
    print("Inverse doesn't exists")
else:
  print("Matrix must be square for determinant, eigenvalues, and inverse")

Determinant :  -2.0000000000000004
Rank :  2
Trace :  5
Eigenvalues :  [-0.37228132  5.37228132]
Eigenvector : 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Inverse : 
 [[-2.   1. ]
 [ 1.5 -0.5]]


### Section 4

In [51]:
import cmath
## •
real = int(input("Enter real part : "))
imag = int(input("Enter imaginary part : "))
z = complex(real,imag)
print(z)

Enter real part : 3
Enter imaginary part : 4
(3+4j)


In [52]:
## •
print(z.conjugate())

(3-4j)


In [53]:
## •
z1 = complex(5,6)
print("Addition : ",z+z1)
print("Subtraction : ",z-z1)
print("Multiplication : ",z*z1)
print("Division : ",z/z1)

Addition :  (8+10j)
Subtraction :  (-2-2j)
Multiplication :  (-9+38j)
Division :  (0.6393442622950819+0.03278688524590165j)


In [54]:
## •
print(z.real,z.imag)

3.0 4.0


In [49]:
## •
print(abs(z))

5.0
